### ISSUE TITLE
reduced still picture header parsing error

### ISSUE THREAD

**Issue by cconcolato** [dwbuiten/obuparse#1]
According to the spec, this line https://github.com/dwbuiten/obuparse/blob/e6e74f6b8e6bfc2c6a671899adff6bb05c4a7137/obuparse.c#L1144
should be setting the value to 0, not 1.

**Comment by dwbuiten** [comment]
Thanks, you're correct, this was a bug.

(There is also, I think, a bug or two in parsing streams with multiple operating points, but I don't have any streams to test with yet - I think @negge had one to give me.)
